#!/bin/sh

err() {
	printf "Error: %s\n" "$@"
	exit 1
}

usage() {
	cat <<EOFUSAGE
$PROGNAME <cmd>
  play
  pause
  stop
  next
  prev
  add
  album
  track
EOFUSAGE
}

cmd() {
	cmd="$1"
	args=""
	shift
	for a in "$@"; do
		[ $(( idx=idx+1 )) -le "$#" ] && args+=", "
		case "${a}" in
			true|false|[0-9]*) args+="${a}" ;;
			*) args+="\"${a}\""
		esac
	done
	printf '{ "command": ["%s"%s] }\n' "$cmd" "$args"
	printf '{ "command": ["%s"%s] }\n' "$cmd" "$args" | $UNIX_SOCK_CMD
}

append() {
	opt="$1"
	shift
	if [ -t 0 ]; then
		for f in "$@"; do
			cmd "loadfile" "${f}" "$opt"
		done
	else
		while read f; do
			cmd "loadfile" "${f}" "$opt"
		done
	fi
}

: ${PROGNAME:="$0"}

if [ -z "$UNIX_SOCK_CMD" ]; then
	if [ -x $(command -v nc) ]; then
		UNIX_SOCK_CMD="nc -U /tmp/mpvd"
	elif [ -x $(command -v socat) ]; then
		UNIX_SOCK_CMD="socat - /tmp/mpvd"
	else
		err "could not find netcat or socat"
	fi
fi

if [ -z "$ALBUM_SEARCH_CMD" ]; then
	if [ -x $(command -v beet) ]; then
		ALBUM_SEARCH_CMD="beet ls -a -p"
	fi
fi

if [ -z "$TRACK_SEARCH_CMD" ]; then
	if [ -x $(command -v beet) ]; then
		TRACK_SEARCH_CMD="beet ls -p"
	fi
fi

if [ -t 0 ]; then
	cmd="$1"
	shift
	case "$cmd" in
		pa|pa[use]*) cmd "set_property" "pause" "true" ;;
		p|p[lay]*) cmd "set_property" "pause" "false" ;;
		s|s[top]*) cmd "stop" ;;
		n|n[ext]*) cmd "playlist-next" ;;
		p|p[rev]*) cmd "playlist-prev" ;;
		add|append) append "$@" ;;
		album) $ALBUM_SEARCH_CMD "$@" | append "append-play" ;;
		track) $TRACK_SEARCH_CMD "$@" | append "append-play" ;;
		*) usage && exit 1 ;;
	esac
else
	append "append-play"
fi
exit 0
